function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function money(v){return "₹"+(Number(v)||0).toLocaleString("en-IN",{maximumFractionDigits:2})}
const $=id=>document.getElementById(id);
let db={plots:[],operations:[],harvests:[],inputs:[],labourers:[]};
function init(){
 try{
  const raw=localStorage.getItem("farmlog-plain-data");
  if(raw){db={...db,...JSON.parse(raw)}}
  else{
   db.plots=[{id:1,crop:"Bitter gourd",variety:"HyVeg Raja",acres:1},{id:2,crop:"Bitter gourd",variety:"VNR 42",acres:1},{id:3,crop:"Tomato",variety:"Syngenta Saaho",acres:1}];
   persist();
  }
  wire();render();
 }catch(e){document.body.innerHTML='<div style="padding:30px;font-family:system-ui"><h2>FarmLog</h2><p>Startup error: '+String(e.message).replace(/</g,"&lt;")+'</p></div>'}
}
function persist(){localStorage.setItem("farmlog-plain-data",JSON.stringify(db))}
function render(){if(!db)return;const ops=db.operations||[],hs=db.harvests||[];const kg=hs.reduce((s,x)=>s+(+x.kg||0),0),sales=hs.reduce((s,x)=>s+(+x.kg||0)*(+x.price||0),0),cost=ops.reduce((s,x)=>s+(+x.cost||0),0);$("seasonSummary").innerHTML='<div class="small">SEASON TO DATE</div><b>'+money(sales)+' gross sales</b><div class="muted">'+kg.toLocaleString()+' kg harvested • '+money(cost)+' operating cost</div>';$("cards").innerHTML='<div class="card">Plots<b>'+db.plots.length+'</b></div><div class="card">Operations<b>'+ops.length+'</b></div><div class="card">Harvest<b>'+kg.toLocaleString()+' kg</b></div><div class="card">Sales<b>'+money(sales)+'</b></div>';
$("today").innerHTML=ops.filter(x=>new Date(x.date).toDateString()===new Date().toDateString()).map(opHTML).join("")||'<div class="empty">Nothing logged today.</div>';$("operationList").innerHTML=ops.slice().reverse().map(opHTML).join("")||'<div class="empty">No work recorded.</div>';$("plotList").innerHTML=db.plots.map(p=>'<div class="item"><div><h3>'+esc(p.crop)+' — '+esc(p.variety)+'</h3><div class="muted">'+(p.acres||0)+' acres</div></div><button type="button" data-edit-plot="'+p.id+'">Edit</button></div>').join("")||'<div class="empty">No plots.</div>';$("labourList").innerHTML=db.labourers.map(p=>'<div class="item"><h3>'+esc(p.name)+'</h3><div class="muted">'+esc(p.role||"General")+' • '+money(p.rate)+'/day</div></div>').join("")||'<div class="empty">No labourers.</div>';$("harvestList").innerHTML=hs.slice().reverse().map(h=>'<div class="item"><div><h3>'+h.kg+' kg @ '+money(h.price)+'/kg</h3><div class="muted">'+esc(h.market||"")+'</div></div><b>'+money(h.kg*h.price)+'</b></div>').join("")||'<div class="empty">No harvest records.</div>';$("reportList").innerHTML=db.plots.map(p=>{let o=ops.filter(x=>String(x.plotId)===String(p.id)),h=hs.filter(x=>String(x.plotId)===String(p.id));let c=o.reduce((s,x)=>s+(+x.cost||0),0),r=h.reduce((s,x)=>s+(+x.kg||0)*(+x.price||0),0);return '<div class="panel"><h3>'+esc(p.crop)+' — '+esc(p.variety)+'</h3><div class="muted">Cost '+money(c)+' • Sales '+money(r)+' • Net '+money(r-c)+'</div></div>'}).join("")}
function opHTML(a){return '<div class="item"><div><h3>'+esc(a.title||a.type)+'</h3><div class="muted">'+esc(a.type)+' • '+new Date(a.date).toLocaleString()+(a.qty?' • '+esc(a.qty)+' '+esc(a.unit||""):"")+'</div></div><b>'+money(a.cost)+'</b></div>'}
function wire(){
 document.querySelectorAll("#nav button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("#nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));$(b.dataset.tab).classList.add("active");render()}));
 document.querySelectorAll("[data-add]").forEach(b=>b.addEventListener("click",()=>openForm(b.dataset.add)));
 $("closeBtn").addEventListener("click",()=>$("modal").classList.remove("show")); document.querySelectorAll("[data-edit-plot]").forEach(b=>b.addEventListener("click",()=>openEditPlot(Number(b.dataset.editPlot))));
 document.querySelectorAll("[data-edit-plot]").forEach(b=>b.addEventListener("click",()=>openEditPlot(Number(b.dataset.editPlot))));
}
function openEditPlot(id){const p=db.plots.find(x=>x.id===id);if(!p)return;$("modalBody").innerHTML='<h2>Edit Plot</h2><label>Crop</label><input id="fCrop" value="'+esc(p.crop)+'"><label>Variety</label><input id="fVar" value="'+esc(p.variety)+'"><label>Area (acres)</label><input id="fAcres" type="number" value="'+(p.acres||0)+'"><button id="saveForm" class="save" type="button">Save changes</button>';$("modal").classList.add("show");$("saveForm").addEventListener("click",async()=>{p.crop=$("fCrop").value;p.variety=$("fVar").value;p.acres=+$("fAcres").value||0;persist();$("modal").classList.remove("show");render()})}
function openForm(type){let body="";if(type==="Harvest")body='<h2>Add Harvest</h2><label>Quantity (kg)</label><input id="fKg" type="number"><label>Price (₹/kg)</label><input id="fPrice" type="number"><label>Market</label><input id="fMarket" placeholder="Chandigarh Mandi"><button id="saveForm" class="save" type="button">Save harvest</button>';else if(type==="Labourer")body='<h2>Add Labourer</h2><label>Name</label><input id="fName"><label>Role</label><input id="fRole"><label>Daily rate</label><input id="fRate" type="number"><button id="saveForm" class="save" type="button">Save labourer</button>';else if(type==="Plot")body='<h2>Add Plot</h2><label>Crop</label><input id="fCrop"><label>Variety</label><input id="fVar"><label>Area (acres)</label><input id="fAcres" type="number"><button id="saveForm" class="save" type="button">Save plot</button>';else body='<h2>Add '+esc(type)+'</h2><label>What was done?</label><input id="fTitle" placeholder="'+esc(type)+' details"><label>Quantity</label><input id="fQty" type="number"><label>Unit</label><input id="fUnit" placeholder="kg / L / workers"><label>Total cost (₹)</label><input id="fCost" type="number"><button id="saveForm" class="save" type="button">Save work</button>';$("modalBody").innerHTML=body;$("modal").classList.add("show");$("saveForm").addEventListener("click",()=>saveForm(type))}
async function saveForm(type){if(type==="Harvest")db.harvests.push({id:Date.now(),date:new Date().toISOString(),kg:+$("fKg").value||0,price:+$("fPrice").value||0,market:$("fMarket").value});else if(type==="Labourer")db.labourers.push({id:Date.now(),name:$("fName").value,role:$("fRole").value,rate:+$("fRate").value||0});else if(type==="Plot")db.plots.push({id:Date.now(),crop:$("fCrop").value,variety:$("fVar").value,acres:+$("fAcres").value||0});else db.operations.push({id:Date.now(),date:new Date().toISOString(),type,title:$("fTitle").value||type,qty:$("fQty").value,unit:$("fUnit").value,cost:+$("fCost").value||0});await persist();$("modal").classList.remove("show");render()}
window.addEventListener("DOMContentLoaded",init);