"use strict";
const KEY="farmlog-redesign-v2";
let db={plots:[],work:[],harvests:[]};
const $=id=>document.getElementById(id);
const money=n=>"₹"+(Number(n)||0).toLocaleString("en-IN",{maximumFractionDigits:2});
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function load(){try{const x=localStorage.getItem(KEY);if(x)db={...db,...JSON.parse(x)}}catch(e){}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function pn(id){const p=db.plots.find(x=>String(x.id)===String(id));return p?p.crop+" — "+p.variety:"Unassigned"}
function totals(){let sales=db.harvests.reduce((s,h)=>s+(+h.kg||0)*(+h.price||0),0),cost=db.work.reduce((s,w)=>s+(+w.cost||0),0),kg=db.harvests.reduce((s,h)=>s+(+h.kg||0),0);return{sales,cost,kg,net:sales-cost}}
function render(){let t=totals();$("net").textContent=money(t.net);$("sales").textContent=money(t.sales);$("cost").textContent=money(t.cost);$("kg").textContent=t.kg.toLocaleString()+" kg";$("plotCount").textContent=db.plots.length;$("workCount").textContent=db.work.length;$("harvestCount").textContent=db.harvests.length;$("plotList").innerHTML=db.plots.map(p=>'<div class="row"><div><b>'+esc(p.crop)+' — '+esc(p.variety)+'</b><small>'+p.acres+' acres</small></div><button data-edit="'+p.id+'">Edit</button><button data-del="'+p.id+'">Delete</button></div>').join("")||'<p class="empty">No plots yet.</p>';$("workList").innerHTML=db.work.slice().reverse().map(w=>'<div class="row"><div><b>'+esc(w.title||w.type)+'</b><small>'+new Date(w.date).toLocaleDateString()+" • "+esc(pn(w.plotId))+'</small></div><strong>'+money(w.cost)+'</strong></div>').join("")||'<p class="empty">No work recorded.</p>';$("harvestList").innerHTML=db.harvests.slice().reverse().map(h=>'<div class="row"><div><b>'+h.kg+' kg @ '+money(h.price)+'/kg</b><small>'+new Date(h.date).toLocaleDateString()+" • "+esc(pn(h.plotId))+" • "+esc(h.market||"")+'</small></div><strong>'+money(h.kg*h.price)+'</strong></div>').join("")||'<p class="empty">No harvest recorded.</p>';document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>plotForm(+b.dataset.edit));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>delPlot(+b.dataset.del))}
function nav(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("on",x.id===id));document.querySelectorAll(".nav button").forEach(x=>x.classList.toggle("on",x.dataset.page===id))}
function modal(title,html,fn){$("title").textContent=title;$("bodyform").innerHTML=html+'<div class="actions"><button id="cancel">Cancel</button><button id="save">Save</button></div>';$("modal").classList.add("on");$("cancel").onclick=()=>$("modal").classList.remove("on");$("save").onclick=fn}
function plotForm(id){let p=id?db.plots.find(x=>x.id===id):{};modal(id?"Edit plot":"New plot",'<label>Crop<input id="crop" value="'+esc(p.crop||"")+'"></label><label>Variety<input id="var" value="'+esc(p.variety||"")+'"></label><label>Area (acres)<input id="acres" type="number" step=".01" value="'+(p.acres||"")+'"></label>',()=>{let q=id?p:{id:Date.now()};q.crop=$("crop").value.trim();q.variety=$("var").value.trim();q.acres=+$("acres").value||0;if(!q.crop)return alert("Enter crop.");if(!id)db.plots.push(q);save();$("modal").classList.remove("on");render()})}
function entry(type){let opts='<option value="">Unassigned</option>'+db.plots.map(p=>'<option value="'+p.id+'">'+esc(p.crop)+' — '+esc(p.variety)+'</option>').join("");if(type==="harvest")modal("New harvest",'<label>Date<input id="date" type="date" value="'+new Date().toISOString().slice(0,10)+'"></label><label>Plot<select id="plot">'+opts+'</select></label><label>Quantity kg<input id="qty" type="number"></label><label>Price ₹/kg<input id="price" type="number"></label><label>Market<input id="market" placeholder="Chandigarh Mandi"></label>',()=>{db.harvests.push({id:Date.now(),date:new Date($("date").value+"T12:00:00").toISOString(),plotId:$("plot").value,kg:+$("qty").value||0,price:+$("price").value||0,market:$("market").value});save();$("modal").classList.remove("on");render()});else modal(type==="expense"?"New expense":type==="fertigation"?"New fertigation":"New work",'<label>Date<input id="date" type="date" value="'+new Date().toISOString().slice(0,10)+'"></label><label>Plot<select id="plot">'+opts+'</select></label><label>Description<input id="desc"></label><label>Cost ₹<input id="cost" type="number"></label><label>Notes<textarea id="notes"></textarea></label>',()=>{db.work.push({id:Date.now(),date:new Date($("date").value+"T12:00:00").toISOString(),plotId:$("plot").value,title:$("desc").value,type,cost:+$("cost").value||0,note:$("notes").value});save();$("modal").classList.remove("on");render()})}
function delPlot(id){if(confirm("Delete this plot?")){db.plots=db.plots.filter(p=>p.id!==id);db.work.forEach(x=>{if(+x.plotId===id)x.plotId=""});db.harvests.forEach(x=>{if(+x.plotId===id)x.plotId=""});save();render()}}
function wire(){document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>nav(b.dataset.page));document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>b.dataset.add==="plot"?plotForm():entry(b.dataset.add));$("add").onclick=()=>entry("work");$("close").onclick=()=>$("modal").classList.remove("on")}
load();wire();render();